# Generated by Django 3.2.2 on 2021-05-07 08:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Regular ', 'REGULAR'), ('Square', 'SQUARE')], default=[], max_length=15),
        ),
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Regular ', 'REGULAR'), ('Square', 'SQUARE')], default=[], max_length=15),
        ),
    ]
