# Generated by Django 3.2.2 on 2021-05-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizza_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Regular', 'REGULAR'), ('Medium', 'MEDIUM'), ('Large', 'LARGE'), ('Extra_Large', 'EXTRA_LARGE')], default=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('Regular ', 'REGULAR'), ('Square', 'SQUARE')], default=[], max_length=255),
        ),
    ]
