# Generated by Django 3.2.2 on 2021-05-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_veg_toppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veg_Toppings',
            new_name='VegToppings',
        ),
    ]
