# Generated by Django 3.2.2 on 2021-05-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_rename_veg_toppings_vegtoppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonVegToopings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
    ]
