# Generated by Django 3.2.2 on 2021-05-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_nonvegtoopings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='veg_toppings',
            field=models.ManyToManyField(to='pizza.VegToppings'),
        ),
    ]
