# Generated by Django 3.2.2 on 2021-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_pizza_veg_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='non_Veg_toppings',
            field=models.ManyToManyField(to='pizza.NonVegToopings'),
        ),
    ]
