# Generated by Django 3.2 on 2021-05-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_pizza_non_veg_toppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonvegtoopings',
            old_name='Name',
            new_name='NonVeg',
        ),
        migrations.RenameField(
            model_name='vegtoppings',
            old_name='Name',
            new_name='Veg',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='non_Veg_toppings',
            field=models.ManyToManyField(related_name='Name', to='pizza.NonVegToopings'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='veg_toppings',
            field=models.ManyToManyField(related_name='Name', to='pizza.VegToppings'),
        ),
    ]
