# Generated by Django 3.2 on 2021-05-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_auto_20210507_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='non_Veg_toppings',
            field=models.ManyToManyField(to='pizza.NonVegToopings'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='veg_toppings',
            field=models.ManyToManyField(to='pizza.VegToppings'),
        ),
    ]
